// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0kNzHWzxq5u3Q4NmAN4R-vs3TH9QRSvA',
    appId: '1:224624216773:android:4a6911fc6bf8e2a7eb7eac',
    messagingSenderId: '224624216773',
    projectId: 'wechat-57a43',
    storageBucket: 'wechat-57a43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvNdEDrCrliBm7Zi61SyJAl0bGxTlPDTA',
    appId: '1:224624216773:ios:522a975fca964bd4eb7eac',
    messagingSenderId: '224624216773',
    projectId: 'wechat-57a43',
    storageBucket: 'wechat-57a43.firebasestorage.app',
    androidClientId: '224624216773-rdio6741q96m6ne8rk9uhlrvsqaiqqt1.apps.googleusercontent.com',
    iosClientId: '224624216773-hsepj7mpadpk048i2s589qr93n1bmq45.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

}